#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Nov 16 15:44:41 PST 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 522f16a0325943acb3243db213d221ad --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot EncipherTeaTb_behav xil_defaultlib.EncipherTeaTb -log elaborate.log"
xelab -wto 522f16a0325943acb3243db213d221ad --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot EncipherTeaTb_behav xil_defaultlib.EncipherTeaTb -log elaborate.log

